landreg_knowman:
    resource: "@LandregKnowmanBundle/Resources/config/routing.yml"
    prefix:   /

# AcmeDemoBundle routes (to be removed)

_cmf_create:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"
