services:
    langreg.knowman.admin.content_item:
        class: Landreg\Bundle\KnowmanBundle\Admin\ItemAdmin
        arguments:
            - ''
            - Landreg\Bundle\KnowmanBundle\Document\Item
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Basic CMS', label: "Item" }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    langreg.knowman.phpcr.initializer:
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        arguments:
            - "Landreg Knowman Basepaths"
            - [ "/knowman/item"]
            - ~
        tags:
            - { name: "doctrine_phpcr.initializer" }