services:
    langreg.knowman.admin.content_item:
        class: Landreg\Bundle\KnowmanBundle\Admin\PageAdmin
        arguments:
            - ''
            - Landreg\KnowmanBundle\Document\Page
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Basic CMS', label: "Item" }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]
    langreg.knowman.admin.topic:
        class: Landreg\Bundle\KnowmanBundle\Admin\PostAdmin
        arguments:
            - ''
            - Landreg\KnowmanBundle\Document\Post
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Basic CMS', label: 'Topic' }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]